/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDisk.h>

@interface DUDiskListSeparator : DUDisk
{
}

- (id)displayName;
- (id)uncachedDisplayIcon;
- (id)toolTipString;
- (int)calculateDUDiskType;
- (BOOL)canSelect;
- (BOOL)hasSpecialOutlineViewDrawing;
- (BOOL)outlineViewCellIsEnabled;
- (BOOL)hasParentDisk;
- (void)diskOneLineDescription;

@end

