/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDisk.h>

@class NSString;

@interface DUDiskPseudoDisk : DUDisk
{
    long long pseudoDiskNumber;
    NSString *pseudoIdentifier;
    NSString *lastSavedName;
    BOOL parentIsRAIDMaster;
    DUDisk *cachedParentDisk;
}

- (id)initWithDUDisk:(id)arg1;
- (void)dealloc;
- (void)setPseudoIdentifier:(id)arg1;
- (id)pseudoIdentifier;
- (void)setParentIsRAIDMaster:(BOOL)arg1;
- (unsigned long long)pseudoDiskNumber;
- (id)uncachedDisplayIcon;
- (id)displayName;
- (id)toolTipString;
- (int)calculateDUDiskType;
- (id)diskDisplayType;
- (struct __DADisk *)theDADisk;
- (void)invalidateCachedData;
- (int)duObjectClass;
- (void)diskOneLineDescription;
- (void)diskFullDescription;
- (const char *)di;
- (id)parentDisk;
- (BOOL)hasParentDisk;
- (id)children;
- (BOOL)hasChildren;
- (void)updateChildren;
- (BOOL)needsChildrenUpdate;
- (void)setNeedsChildrenUpdate:(BOOL)arg1;
- (id)fsckHistoryNoChildren;
- (id)fsckHistory;
- (void)setFsckHistory:(id)arg1;
- (BOOL)clearFsckHistory;
- (id)wholeDiskName;
- (struct __CFDictionary *)registryProps;
- (long long)partitionID;
- (BOOL)deviceIsOpen;
- (id)diskIdentifier;
- (BOOL)isVirtualOnly;
- (id)deviceNode;
- (id)rawDeviceNode;
- (id)mountPoint;
- (id)volumeName;
- (id)filesystem;
- (id)filesystemType;
- (id)ioContent;
- (id)deviceTreePath;
- (id)bayName;
- (id)UUID;
- (id)internalUUID;
- (id)diskArbInfoDict;
- (id)mediaName;
- (unsigned long long)flags;
- (BOOL)isWritableMedia;
- (BOOL)isWritableVolume;
- (BOOL)isEjectable;
- (BOOL)isWhole;
- (BOOL)isNetworkDisk;
- (BOOL)isNonLeaf;
- (BOOL)isCDROM;
- (BOOL)isDVDROM;
- (BOOL)isOpticalDisc;
- (BOOL)isOpticalDevice;
- (BOOL)isJournaled;
- (BOOL)isErasableOpticalMedia;
- (id)opticalMediaType;
- (id)deviceName;
- (long long)isInternal;
- (id)opticalDeviceType;
- (BOOL)isRAIDMaster;
- (BOOL)isRAIDSlice;
- (id)RAIDSequenceNumber;
- (unsigned long long)RAIDSliceNumber;
- (unsigned long long)RAIDSetSliceCount;
- (id)smartStatus;
- (id)busSpecificKeys;
- (id)RAIDSetUUID;
- (id)RAIDMemberUUID;
- (id)RAIDSetLevelType;
- (id)RAIDSetName;
- (id)RAIDSetStatus;
- (id)RAIDMemberStatus;
- (id)RAIDMemberType;
- (id)RAIDSetProperties;
- (id)RAIDMemberProperties;
- (id)RAIDMembers;
- (id)RAIDSpares;
- (id)ioKitSize;
- (id)blockSize;
- (id)partitionStartLocation;
- (unsigned long long)totalSize;
- (unsigned long long)freeSpace;
- (unsigned long long)rawSize;
- (id)protocol;
- (id)mediaType;
- (unsigned long long)partitionNumber;
- (unsigned long long)diskNumber;
- (BOOL)permissionsEnabled;
- (BOOL)canBeRestoreSource;
- (BOOL)canBeRestoreTarget:(BOOL)arg1;
- (BOOL)mountAllowed;
- (BOOL)canRepairPermissions;
- (BOOL)canBeVerified;
- (BOOL)canBeRepaired;
- (BOOL)isPseudoDisk;
- (BOOL)parentIsRAIDMaster;
- (BOOL)isXsanDisk;
- (BOOL)isDVDRAM;

@end

