/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDisk.h>

@interface DUDiskSavedDiskRepresentation : DUDisk
{
}

- (int)duObjectClass;
- (void)diskFullDescription;
- (id)toolTipString;
- (int)calculateDUDiskType;
- (id)diskDisplayType;
- (BOOL)canBeRemovedByUser;

@end

