/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDisk.h>

@interface DUDisk (DMDiskExtended)
+ (id)diskTypeName:(int)arg1;
- (id)partitionStartLocation;
- (id)calculateUsedBytes;
- (id)calculateFreeBytes;
- (id)resizeProperties;
- (void)setResizeProperties:(id)arg1;
- (BOOL)isRootDisk;
- (BOOL)isDiskImage;
- (BOOL)isHTTPDiskImage;
- (BOOL)isNonAppleDiskImage;
- (BOOL)isOpticalDevice;
- (BOOL)isFireWireDisk;
- (BOOL)isUSBDisk;
- (BOOL)isATADisk;
- (BOOL)isSCSIDisk;
- (BOOL)isSATADisk;
- (BOOL)isSASDisk;
- (BOOL)isDVDRAM;
- (BOOL)isFibreChannelDisk;
- (BOOL)isBootVolume;
- (BOOL)needsPseudoPartitionDisk;
- (BOOL)isPseudoDisk;
- (BOOL)parentIsRAIDMaster;
- (BOOL)isOfflineDiskImage;
- (BOOL)isEncryptedDiskImage;
- (BOOL)canBeRestoreSource;
- (BOOL)canBeRestoreTarget:(BOOL)arg1;
- (BOOL)supportsPacketWriting;
- (BOOL)hasBlankOpticalMedia;
- (BOOL)isTransientDisk;
- (BOOL)supportsLiveResize;
- (id)imageName;
- (id)imagePath;
- (id)diskImagePath;
- (id)internalUUID;
- (BOOL)hasSMARTError;
- (id)localizedSMARTStatus:(long long *)arg1;
- (id)connectionIDDictionary;
- (id)localizedSocketType;
- (id)localizedProtocol;
- (id)localizedRAIDSetStatus;
- (id)localizedRAIDMemberStatus;
- (id)localizedRAIDSetLevelType;
- (id)localizedMediaType;
- (id)buildWWNString:(id)arg1;
@end

