/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUModuleManager.h>

@interface DUModuleManager (_private)
- (void)findDUModules:(id)arg1;
- (id)modules;
- (id)orderedListOfModules;
@end

