/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUNamer.h>

@interface DUNamer (_private)
- (id)name;
- (id)nameForFAT;
- (id)convertToFAT:(id)arg1;
- (id)defaultName;
- (id)defaultFATName;
- (id)userEnteredName;
- (id)userEnteredNameForFAT;
- (id)validCharacters;
- (id)stripInvalidHFSCharacters:(id)arg1;
- (id)stripInvalidFATCharacters:(id)arg1;
@end

