/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol DUPluginProtocol
- (void)moduleDidLoad;
- (id)dm;
- (id)diskController;
- (id)windowController;
- (id)parentTabView;
- (id)parentTabViewItem;
- (id)utilityView;
- (void)setWindowController:(id)arg1;
- (void)setParentTabView:(id)arg1;
- (void)setParentTabViewItem:(id)arg1;
- (BOOL)currentActiveTab;
- (void)setActiveTab;
- (id)warnOnClose;
- (id)warnOnQuit;
- (id)warnOnSwitch;
- (BOOL)canPrint;
- (void)printModuleSpecific:(id)arg1;
- (void)helpButtonAction:(id)arg1;
- (id)dataType;
- (BOOL)shouldRunOnThisConfig;
- (id)tabOrder;
- (id)displayName;
- (void)registerForNotifications;
- (void)selectionDidChange:(id)arg1;
- (void)becomeSelectedTab;
- (void)deselectTab;
- (void)parentTabViewChanged:(id)arg1;
@end

