/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUVFSEventHandler.h"

@interface DUVFSEventHandler (DUPrivate)
- (void)runVFSNotificationHandler;
- (long long)vfsevent_init;
- (unsigned long long)vfsevent_wait:(long long)arg1 withTimeout:(long long)arg2;
- (void)checkDisksForChange;
@end

