/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/ProgressViewController.h>

@interface ProgressViewController (Accessors)
- (id)view;
- (id)progressView;
- (id)alertView;
- (id)separator;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (SEL)progressSkipSelector;
- (void)setProgressSkipSelector:(SEL)arg1;
- (SEL)progressCancelSelector;
- (void)setProgressCancelSelector:(SEL)arg1;
- (SEL)alertOKSelector;
- (void)setAlertOKSelector:(SEL)arg1;
- (SEL)alertCancelSelector;
- (void)setAlertCancelSelector:(SEL)arg1;
- (id)context;
- (void)setContext:(id)arg1;
@end

