/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/ProgressViewController.h>

@interface ProgressViewController (Actions)
- (void)doProgressCancel:(id)arg1;
- (void)doProgressSkip:(id)arg1;
- (void)doAlertCancel:(id)arg1;
- (void)doAlertOK:(id)arg1;
- (void)skipOrCancelSelector:(id)arg1;
- (void)invokeSelector:(SEL)arg1 withItem:(id)arg2;
@end

