/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol ProgressViewProtocol
- (void)showProgressView;
- (void)setProgressCancelEnabled:(BOOL)arg1;
- (void)setProgressCancelEnabledLite:(BOOL)arg1;
- (BOOL)progressCancelEnabled;
- (void)setProgressCancelButtonTitle:(id)arg1;
- (id)progressCancelButtonTitle;
- (void)setProgressSkipEnabled:(BOOL)arg1;
- (void)setProgressSkipEnabledLite:(BOOL)arg1;
- (BOOL)progressSkipEnabled;
- (void)setProgressSkipButtonTitle:(id)arg1;
- (id)progressSkipButtonTitle;
- (id)progressPrimaryText;
- (void)setProgressPrimaryText:(id)arg1;
- (id)progressSecondaryText;
- (void)setProgressSecondaryText:(id)arg1;
- (id)progressTertiaryText;
- (void)setProgressTertiaryText:(id)arg1;
- (double)progressPercentDone;
- (void)setProgressPercentDone:(double)arg1;
- (BOOL)progressIsDeterminate;
- (void)setProgressIsDeterminate:(BOOL)arg1;
- (BOOL)progressCancelPending;
- (void)setProgressCancelPending:(BOOL)arg1;
- (BOOL)progressSkipPending;
- (void)setProgressSkipPending:(BOOL)arg1;
- (void)showAlertView;
- (void)showAlertViewWithSound:(BOOL)arg1 withDockBounce:(BOOL)arg2 withMakeKeyAndOrderFront:(BOOL)arg3;
- (void)setAlertImage:(id)arg1;
- (void)setAlertCancelEnabled:(BOOL)arg1;
- (void)setAlertCancelEnabledLite:(BOOL)arg1;
- (BOOL)alertCancelEnabled;
- (void)setAlertCancelButtonTitle:(id)arg1;
- (id)alertCancelButtonTitle;
- (void)setAlertOKEnabled:(BOOL)arg1;
- (BOOL)alertOKEnabled;
- (void)setAlertOKButtonTitle:(id)arg1;
- (id)alertOKButtonTitle;
- (id)alertMessageString;
- (void)setAlertMessageString:(id)arg1;
- (id)alertTitleString;
- (void)setAlertTitleString:(id)arg1;
- (BOOL)alertCancelPending;
- (void)setAlertCancelPending:(BOOL)arg1;
- (BOOL)alertOKPending;
- (void)setAlertOKPending:(BOOL)arg1;
- (BOOL)needsWarningOnQuit;
- (void)setNeedsWarningOnQuit:(BOOL)arg1;
@end

