/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSoundDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSLock, NSMutableArray, NSScrollView, NSString, NSView, NSWindow;

@interface ProgressController : NSObject <NSWindowDelegate, NSSoundDelegate>
{
    NSWindow *_window;
    NSScrollView *_scrollView;
    NSView *_scrollDocumentView;
    NSMutableArray *_progressViews;
    BOOL _isSheet;
    NSWindow *_parent;
    NSString *_windowTitle;
    NSString *_frameAutosaveName;
    BOOL _recentAtTop;
    BOOL _cachedRecentAtTop;
    BOOL _animateInitialAppearance;
    BOOL _animateResizing;
    BOOL _excludeFromWindowsMenu;
    BOOL _usesSound;
    NSLock *_lock;
    NSMutableArray *_pendingAdds;
    NSMutableArray *_pendingRemoves;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (id)addAlertViewTo:(id)arg1 withMessage:(id)arg2 allowOK:(BOOL)arg3 okButtonTitle:(id)arg4 allowCancel:(BOOL)arg5 cancelButtonTitle:(id)arg6 usingDelegate:(id)arg7 andOKSelector:(SEL)arg8 andCancelSelector:(SEL)arg9 andContext:(id)arg10;
- (id)addMessageViewTo:(id)arg1 withMessage:(id)arg2 allowOK:(BOOL)arg3 okButtonTitle:(id)arg4 allowCancel:(BOOL)arg5 cancelButtonTitle:(id)arg6 usingDelegate:(id)arg7 andOKSelector:(SEL)arg8 andCancelSelector:(SEL)arg9 andContext:(id)arg10;
- (id)addProgressViewTo:(id)arg1 withMessage:(id)arg2 withInformationText:(id)arg3 allowCancel:(BOOL)arg4 cancelButtonTitle:(id)arg5 allowSkip:(BOOL)arg6 skipButtonTitle:(id)arg7 isDeterminate:(BOOL)arg8 usingDelegate:(id)arg9 andCancelSelector:(SEL)arg10 andSkipSelector:(SEL)arg11 andContext:(id)arg12;
- (void)addProgressView:(id)arg1 wasPending:(BOOL)arg2;
- (void)_showWindow;
- (void)_checkForMoreWork;
- (void)removeProgressView:(id)arg1;
- (void)removeProgressView:(id)arg1 wasPending:(BOOL)arg2;
- (void)_fixSeparators;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;

@end

