/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/ZFSXSImageTextAndDetailCell.h>

@interface ZFSXSTextAndDetailCell : ZFSXSImageTextAndDetailCell
{
}

- (id)init;
- (id)initWithCoder:(id)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;

@end

