/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/ZFSXSImageAndTextCell.h>

@class NSString, NSValueTransformer;

@interface ZFSXSImageTextAndDetailCell : ZFSXSImageAndTextCell
{
    NSString *_subtitle;
    NSString *_subtitleKeyPath;
    NSValueTransformer *_subtitleValueTransformer;
    NSString *_subtitleValueTransformerClassName;
    struct CGRect _subtitleRect;
}

+ (void)initialize;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setObjectValue:(id)arg1;
- (id)attributedSubtitle;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)subtitleRectForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(retain) NSString *subtitleValueTransformerClassName; // @synthesize subtitleValueTransformerClassName=_subtitleValueTransformerClassName;
@property(retain) NSValueTransformer *subtitleValueTransformer; // @synthesize subtitleValueTransformer=_subtitleValueTransformer;
@property(retain) NSString *subtitleKeyPath; // @synthesize subtitleKeyPath=_subtitleKeyPath;
@property(retain) NSString *subtitle; // @synthesize subtitle=_subtitle;

@end

