/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface _DMListDA : NSObject
{
    double _givenTimeout;
    struct __DASession *_givenDASession;
    BOOL _currentDAIdle;
    NSMutableArray *_currentList;
    NSString *_searchKey;
    id _searchValue;
    BOOL _didItOnce;
}

+ (struct __DADisk *)waitAndCopyDiskForBSD:(id)arg1 daSession:(struct __DASession *)arg2 timeout:(double)arg3 preWait:(double)arg4;
- (id)initWithSession:(struct __DASession *)arg1 timeout:(double)arg2;
- (void)dealloc;
- (void)doBlockingSearch;
- (struct __DADisk *)copyCurrentDiskForKey:(id)arg1 value:(id)arg2;
- (id)copyCurrentDisks;
- (BOOL)anticipatingMoreDisks;

@end

