/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#pragma mark Named Structures

struct DMUDSPrivRec {
    unsigned int signature_LE32;
    unsigned char nothing;
    char bsd[150];
    unsigned int appleRAIDUUIDKind_LE32;
    char appleRAIDUUID[40];
    unsigned int zfsUUIDKind_LE32;
    char zfsUUID[40];
};

