/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class DMManager;

@interface DMEraseDiskPrivVars : NSObject
{
    struct __DASession *_clientDASession;
    id <DMAsyncDelegate> _clientDelegate;
    DMManager *_dmManager;
    char _sessionUUID[40];
    unsigned int _sessionF2Tport;
    unsigned int _sessionT2Fport;
}

@end

