/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface DMEraseDisk : NSObject
{
    id _instPriv;
}

+ (id)eraseTypesForDisk:(struct __DADisk *)arg1;
+ (id)defaultFilesystemForDisk:(struct __DADisk *)arg1;
- (id)init;
- (id)initWithManager:(id)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)cancelCurrentOperation;
- (id)eraseDisk:(struct __DADisk *)arg1 synchronous:(BOOL)arg2 filesystem:(id)arg3 bootable:(BOOL)arg4 name:(id)arg5 doNewfs:(BOOL)arg6;
- (int)zeroDisk:(struct __DADisk *)arg1 random:(BOOL)arg2 howMany:(unsigned int)arg3;
- (int)securelyEraseDisk:(struct __DADisk *)arg1 level:(int)arg2;
- (int)securelyEraseFreespace:(struct __DADisk *)arg1 level:(int)arg2;
- (int)eraseOpticalAsync:(struct __DADisk *)arg1 quick:(BOOL)arg2 format:(BOOL)arg3;

@end

