/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface DMFilesystem : NSObject
{
    id _instPriv;
}

+ (void)ensureDatabaseAndForceRebuild:(BOOL)arg1;
+ (id)filesystems;
+ (id)bootableFilesystems;
+ (id)filesystemForLocalizedName:(id)arg1;
+ (id)filesystemForType:(id)arg1 considerDisk:(struct __DADisk *)arg2;
+ (id)filesystemForIOContent:(id)arg1;
+ (id)filesystemForPersonality:(id)arg1;
+ (BOOL)isCanonicalPersonalityNameEqual:(id)arg1 withInformalName:(id)arg2;
- (id)initWithName:(id)arg1 type:(id)arg2 localized:(id)arg3 dictionary:(id)arg4 bundlePath:(id)arg5;
- (void)dealloc;
- (id)description;
- (id)filesystemPersonality;
- (id)filesystemType;
- (id)userVisibleName;
- (id)userVisibleNameForLanguage:(id)arg1;
- (id)filesystemDictionary;
- (BOOL)shouldBeUserFormattable;
- (BOOL)serverOnly;
- (BOOL)nameSanitizer:(id)arg1 correctedName:(id *)arg2 illegalChars:(id)arg3 legalChars:(id)arg4 leadingDotOK:(BOOL)arg5 maxLen:(unsigned int)arg6 limitEncoding:(unsigned long long)arg7;
- (BOOL)isValidName:(id)arg1;
- (BOOL)isValidName:(id)arg1 correctedName:(id *)arg2;
- (id)bundlePath;
- (id)contentMask;
- (id)verifyExecutable;
- (id)verifyArguments;
- (id)liveVerifyArguments;
- (id)percentageVerifyArguments;
- (id)verifyRepairOutputXMLArguments;
- (BOOL)supportsPercentageVerifies;
- (BOOL)supportsXMLVerifies;
- (BOOL)canBeVerified;
- (id)repairExecutable;
- (id)repairArguments;
- (BOOL)canBeRepaired;
- (id)formatExecutable;
- (id)formatArguments;
- (BOOL)canBeFormatted;
- (id)minimumSize;
- (id)maximumSize;
- (BOOL)canFormatWholeDisk;
- (BOOL)requiresBooterToBoot;
- (BOOL)requiresWholeDiskFormat;
- (BOOL)bootable;
- (BOOL)canHavePermissionsOff;
- (BOOL)supportsJournaling;
- (BOOL)supportsLiveVerify;
- (BOOL)supportsResize;
- (void)setVerifyRepairStringLocale:(id)arg1;
- (id)localizedVerifyRepairString:(id)arg1 found:(char *)arg2;

@end

