/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DiskManagement/DMManager.h>

@interface DMManager (PrivateMethods)
- (unsigned long long)setDelegate:(id)arg1;
- (void)removeDelegate:(id)arg1;
- (void)stopInstanceAsNeeded;
- (void)getSessionUUID:(char *)arg1 f2tPort:(unsigned int *)arg2 t2fPort:(unsigned int *)arg3 clientDefaultDASession:(struct __DASession **)arg4;
- (struct __DASession *)obtainedClientDASession:(struct __DADisk *)arg1;
@end

