/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DiskManagement/DMManager.h>

@interface DMManager (Volume)
- (int)upgradeDisk:(struct __DADisk *)arg1 enablePermissions:(BOOL)arg2;
- (int)moveJournalInternal:(struct __DADisk *)arg1;
- (int)modifyJournalOnDisk:(struct __DADisk *)arg1 enableJournaling:(BOOL)arg2 force:(BOOL)arg3;
- (int)modifyOwnershipForDisk:(struct __DADisk *)arg1 enableOwnership:(BOOL)arg2;
@end

