/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DiskManagement/DMManager.h>

@interface DMManager (Info)
- (struct __DADisk *)diskForArgumentName:(id)arg1 timeout:(double)arg2 complete:(char *)arg3;
- (struct __DADisk *)diskForPath:(id)arg1 error:(int *)arg2;
- (struct __DADisk *)diskForMountPoint:(id)arg1 error:(int *)arg2;
- (struct __DADisk *)rootDisk:(int *)arg1;
- (id)disks;
- (id)topLevelDisks;
- (id)childrenForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)directChildrenForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (struct __DADisk *)wholeDiskForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)descriptionForDisk:(struct __DADisk *)arg1;
- (BOOL)isWholeDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)uuidForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)deviceNameForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)mediaNameForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)diskIdentifierForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)wholeDiskIdentifierForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)partitionIdentifierForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)deviceNodeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)rawDeviceNodeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)deviceTreePathForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isRootVolume:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isOnSameWholeDiskAsRoot:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isMountedVolume:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)mountPointForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)volumeNameForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (struct __DADisk *)diskForVolumeName:(id)arg1 error:(int *)arg2;
- (id)volumeFreeSpaceForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)ioKitSizeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)totalSizeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)blockSizeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isWritableDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isWritableMedia:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isWritableVolume:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isEjectableDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)filesystemForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isOpticalDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isCD:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isDVD:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)opticalDeviceTypeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)opticalMediaTypeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isErasableOpticalMedia:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)bayNameForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isAppleDiskImage:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)mediaTypeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isIPodDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isXsanComponentDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isXsanFilesystemDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)protocolForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)busSpecificKeysForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)smartStatusForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)wholeDiskHasOS9Drivers:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)wholeDiskSupportsLowLevelFormat:(struct __DADisk *)arg1 error:(int *)arg2;
- (int)partitionMapSchemeForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isSystemImage:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isUserDataVolume:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isNetworkDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isInternalDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isJournaledDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isLeafDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isOpenDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isLiveResizablePartitionForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)permissionsEnabledForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)canRepairPermissions:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)ioContentToHuman:(id)arg1 context:(id)arg2 error:(int *)arg3;
- (id)ioContentOfDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isMountableVolume:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)DMAppleRAIDUUIDForDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (struct __DADisk *)DMAppleRAIDUUIDLookup:(id)arg1;
- (BOOL)isAppleRAIDUUID:(id)arg1 error:(int *)arg2;
- (BOOL)isAppleRAIDDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isAppleRAIDSetDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isAppleRAIDMemberDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (BOOL)isAppleRAIDSpareDisk:(struct __DADisk *)arg1 error:(int *)arg2;
- (id)DMAppleRAIDParentUUIDForUUID:(id)arg1 error:(int *)arg2;
- (id)DMAppleRAIDMemberRebuildProgress:(id)arg1 error:(int *)arg2;
@end

