/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "DUOutlineControllerProtocol-Protocol.h"

@class DMManager, DUDiskController, DUOutlineView, NSMutableArray, NSScrollView, NSTableColumn, NSTimer;

@interface DUBaseDiskListViewController : NSObject <DUOutlineControllerProtocol>
{
    NSScrollView *scroller;
    DUOutlineView *outlineView;
//    id <winControllerProtocol> winController;
    NSTableColumn *defaultColumn;
    DMManager *dm;
    DUDiskController *diskController;
    NSMutableArray *_selectedDisks;
    NSMutableArray *_selectedVolumes;
    NSMutableArray *_selectedRAIDs;
    BOOL haveDiskData;
    BOOL itemSelectedWithoutError;
    long long iconSize;
    NSTimer *reloadTimer;
}

- (id)dm;
- (id)init;
- (void)dealloc;
- (id)scroller;
- (id)listView;
- (void)setStartupFrame:(struct CGSize)arg1;
- (void)awakeFromNib;
- (id)diskController;
- (void)doneWaitingForDisks:(id)arg1;
- (void)delete:(id)arg1;
- (BOOL)interfaceLock;
- (void)disksChanged:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)fullListReceived:(id)arg1;
- (void)unselectAllDisks:(id)arg1;
- (void)reloadDataCreateTimerOnMainThread:(id)arg1;
- (void)reloadData;
- (void)reloadDataNow:(id)arg1;
- (void)resetSelectedDisks;
- (void)resetSelectedVolumes;
- (void)resetSelectedRAIDs;
- (void)addToSelectedDisks:(id)arg1;
- (void)addToSelectedVolumes:(id)arg1;
- (void)addToSelectedRAIDs:(id)arg1;
- (id)selectedDisks;
- (id)selectedVolumes;
- (id)selectedRAIDs;
- (id)allSelectedItems;
- (id)allSelectedItems:(BOOL)arg1 filterDuplicates:(BOOL)arg2;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (void)outlineView:(id)arg1 willDisplayOutlineCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 willReturnMenu:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)tableViewDidEndDragOutsideBounds:(id)arg1;
- (id)outlineView:(id)arg1 menuForTableColumn:(id)arg2 row:(long long)arg3;

@end

