/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUContextualMenus.h>

@interface DUContextualMenus (private)
- (id)createMenuItem:(id)arg1 withTarget:(id)arg2 withObject:(id)arg3 withAction:(SEL)arg4;
- (id)concatNSMenus:(id)arg1 withMenuItems:(id)arg2;
- (id)diskImagesContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)generalContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)diskFeaturesContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)individualModuleContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)singleModuleContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)debugContextualMenus:(id)arg1 inWindow:(id)arg2;
- (id)activeModule:(id)arg1;
@end

