/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDiskController.h>

@interface DUDiskController (DMManagerExtended)
- (id)rootDiskWithRAIDSetUUID:(id)arg1;
- (id)rootDiskWithRAIDSetSlicePartition:(id)arg1;
- (id)slicePartitionInRAIDSliceDisk:(id)arg1;
- (id)raidSetFromRAIDSliceDisk:(id)arg1;
- (id)diskAtExactPath:(id)arg1;
- (BOOL)diskHasRAIDSliceChildren:(id)arg1;
- (BOOL)diskHasRAIDMemberChildren:(id)arg1;
- (BOOL)diskHasBootPartition:(id)arg1;
- (BOOL)diskIsPartOfRAID:(id)arg1;
@end

