/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDate, NSImage, NSLock, NSMutableArray, NSMutableDictionary, NSString;

@interface DUDisk : NSObject
{
    NSMutableDictionary *miscData;
    int cachedDUDiskType;
    DUDisk *parentDisk;
    BOOL isDisplayedToUser;
    long long indentLevel;
    BOOL needsChildrenUpdate;
    id fsckHistory;
    BOOL ejected;
    BOOL changed;
    DUDisk *pseudoChild;
    NSDate *futureReleaseTime;
    BOOL requestingEjectOrUnmount;
    NSLock *childListLock;
    NSString *cachedDisplayName;
    NSString *cachedStringForOutlineView;
    NSString *cachedStringForSimpleInterfaceList;
    NSImage *cachedDisplayIcon;
    NSString *cachedRAIDSetUUID;
    NSString *cachedRAIDMemberUUID;
    NSString *cachedRAIDParentUUID;
    NSString *cachedRAIDUUID;
    NSString *cachedUUID;
    NSMutableArray *cachedChildrenDisk;
    NSMutableArray *cachedVisibleChildrenDisk;
}

- (id)init;
- (void)dealloc;
- (int)duObjectClass;
- (void)futureRelease;
- (BOOL)shouldReleaseBecauseFutureRelease;
- (BOOL)shouldInvalidateCachedData;
- (void)invalidateCachedData;
- (id)uncachedDisplayIcon;
- (id)displayIcon;
- (id)displayName;
- (id)formattedSessionName;
- (id)stringForOutlineView;
- (id)stringForSimpleInterfaceList;
- (id)toolTipString;
- (int)calculateDUDiskType;
- (int)diskType;
- (id)diskDisplayType;
- (struct __DADisk *)theDADisk;
- (void)setDADisk:(struct __DADisk *)arg1;
- (void)updateData:(id)arg1;
- (void)diskChangedHandler:(id)arg1;
- (id)parentDisk;
- (BOOL)hasParentDisk;
- (void)setParentDisk:(id)arg1;
- (id)rootParentDisk;
- (id)parentIdentifier;
- (void)setPseudoChild:(id)arg1;
- (id)pseudoChild;
- (void)addChild:(id)arg1;
- (void)setDiskNode:(id)arg1;
- (id)diskNode;
- (BOOL)isDisplayedToUser;
- (void)setIsDisplayedToUser:(BOOL)arg1;
- (const char *)di;
- (id)children;
- (void)buildNewChildrenDiskList;
- (BOOL)hasChildren;
- (void)updateChildren;
- (BOOL)needsChildrenUpdate;
- (void)setNeedsChildrenUpdate:(BOOL)arg1;
- (id)visibleChildren;
- (id)visibleChildrenAndSubChildren;
- (id)cachedChildDiskWithDADisk:(struct __DADisk *)arg1;
- (id)fsckHistoryNoChildren;
- (id)fsckHistory;
- (void)setFsckHistory:(id)arg1;
- (BOOL)clearFsckHistory;
- (id)device;
- (void)setDevice:(id)arg1;
- (void)setDiskIdentifier:(id)arg1;
- (BOOL)canDrag;
- (BOOL)canSelect;
- (BOOL)canBeRemovedByUser;
- (BOOL)shouldBeDisplayedInOutlineView;
- (BOOL)hasSpecialOutlineViewDrawing;
- (BOOL)outlineViewCellIsEnabled;
- (BOOL)outlineViewCellCanBeSelected;
- (BOOL)hasOutlineViewColor;
- (void)setRequestEjectOrUnmount:(BOOL)arg1;
- (BOOL)requestingEjectOrUnmount;
- (BOOL)ejected;
- (void)setEjected:(BOOL)arg1;
- (BOOL)changed;
- (void)setChanged:(BOOL)arg1;
- (id)miscData;
- (id)miscDataForKey:(id)arg1;
- (void)setMiscData:(id)arg1 forKey:(id)arg2;
- (id)outlineViewColor;
- (void)diskDescription:(BOOL)arg1;
- (void)diskOneLineDescription;
- (void)diskFullDescription;
- (id)description;
@property(retain) NSMutableArray *cachedVisibleChildrenDisk; // @synthesize cachedVisibleChildrenDisk;
@property(retain) NSMutableArray *cachedChildrenDisk; // @synthesize cachedChildrenDisk;
@property(copy) NSString *cachedUUID; // @synthesize cachedUUID;
@property(copy) NSString *cachedRAIDUUID; // @synthesize cachedRAIDUUID;
@property(copy) NSString *cachedRAIDParentUUID; // @synthesize cachedRAIDParentUUID;
@property(copy) NSString *cachedRAIDMemberUUID; // @synthesize cachedRAIDMemberUUID;
@property(copy) NSString *cachedRAIDSetUUID; // @synthesize cachedRAIDSetUUID;
@property(copy) NSString *cachedStringForSimpleInterfaceList; // @synthesize cachedStringForSimpleInterfaceList;
@property(copy) NSString *cachedStringForOutlineView; // @synthesize cachedStringForOutlineView;
@property(copy) NSString *cachedDisplayName; // @synthesize cachedDisplayName;

@end

