/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUDiskController.h"

@interface DUDiskController (DMManager)
- (BOOL)ejectDisk:(id)arg1 synchronous:(BOOL)arg2;
- (BOOL)unmountDisk:(id)arg1 includeChildren:(BOOL)arg2 synchronous:(BOOL)arg3;
- (BOOL)unmountDisk:(id)arg1 includeChildren:(BOOL)arg2 synchronous:(BOOL)arg3 force:(BOOL)arg4;
- (BOOL)mountDisk:(id)arg1 includeChildren:(BOOL)arg2 synchronous:(BOOL)arg3;
- (long long)modifyJournalOnDisk:(id)arg1 enableJournaling:(BOOL)arg2;
- (unsigned long long)maximumUserPartitions:(id)arg1;
- (id)eraseTypesForDisk:(id)arg1;
- (id)defaultFilesystemForDisk:(id)arg1;
- (id)getPartitionStartLocationForDisk:(id)arg1;
@end

