/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DUDisk.h>

@interface DUDisk (DiskImageObjectMethods)
- (long long)getDiskImageObject:(void **)arg1;
- (long long)getDiskImageObject:(void **)arg1 withErrorString:(id *)arg2;
- (long long)getDiskImageObjectFromPathOrDiskNode:(void **)arg1;
- (long long)getDiskImageObjectFromPathOrDiskNode:(void **)arg1 withErrorString:(id *)arg2;
- (long long)getDiskImageObjectFromPathOrDiskNode:(void **)arg1 unmountingReadWriteVolumesReturning:(id *)arg2;
- (long long)getDiskImageObjectFromPathOrDiskNode:(void **)arg1 unmountingReadWriteVolumesReturning:(id *)arg2 withErrorString:(id *)arg3;
@end

