/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "DUPluginProtocol-Protocol.h"

@class DMManager, DUDisk, NSMenu, NSView;

@interface DUModule : NSObject <DUPluginProtocol>
{
    NSView *utilityView;
    id diskController;
    id windowController;
    id parentTabView;
    id parentTabViewItem;
    NSMenu *_moduleMenu;
    NSMenu *_moduleDockMenu;
    id _menuItem;
    long long _menuLocationIndex;
    BOOL _menuDisplayed;
    DUDisk *workingDisk;
    DMManager *dm;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)cleanup;
- (void)moduleDidLoad;
- (id)dataType;
- (id)dm;
- (BOOL)shouldRunOnThisConfig;
- (id)tabOrder;
- (long long)_compareTabOrder:(id)arg1;
- (id)displayName;
- (id)diskController;
- (id)windowController;
- (id)parentTabView;
- (id)parentTabViewItem;
- (void)setWindowController:(id)arg1;
- (void)setParentTabView:(id)arg1;
- (void)setParentTabViewItem:(id)arg1;
- (id)utilityView;
- (void)setActiveTab;
- (BOOL)currentActiveTab;
- (id)warnOnClose;
- (id)warnOnQuit;
- (id)warnOnSwitch;
- (BOOL)windowShouldClose:(id)arg1;
- (BOOL)canPrint;
- (void)printModuleSpecific:(id)arg1;
- (void)helpButtonAction:(id)arg1;
- (void)registerForNotifications;
- (void)selectionDidChange:(id)arg1;
- (void)windowChangedNotication:(id)arg1;
- (void)diskChangedHandler:(id)arg1;
- (void)diskReplacedByHandler:(id)arg1;
- (void)notifyModuleOfEvent:(id)arg1 diskNotification:(id)arg2;
- (void)setRunning:(BOOL)arg1;
- (id)workingDisk;
- (void)setWorkingDisk:(id)arg1;
- (void)enableButtons;
- (void)disableAllButtons;
- (void)sendCompletionReport:(id)arg1;
- (void)clearMatrix:(id)arg1;
- (void)becomeSelectedTab;
- (void)simpleModuleAlert:(id)arg1 msg:(id)arg2 err:(long long)arg3;
- (void)deselectTab;
- (BOOL)validateMenuItem:(id)arg1;
- (void)parentTabViewChanged:(id)arg1;
- (id)rootDiskForPartition:(id)arg1;
- (id)partitionsForRootDisk:(id)arg1;
- (BOOL)displayPanelForDiskType:(int)arg1 andDisk:(id)arg2;
- (int)panelDisplayModeForDiskType:(int)arg1 andDisk:(id)arg2;
- (id)instructionalTextParagraphStyle;
- (id)instructionalTextParagraphStyleNoIndent;

@end

