/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface DUModuleManager : NSObject
{
    NSMutableDictionary *modules;
    NSMutableArray *orderedList;
    NSMutableArray *orderedModuleList;
}

+ (id)newModuleForType:(id)arg1;
- (void)dealloc;
- (id)orderedModuleListOfModules;

@end

