/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCharacterSet, NSMutableDictionary;

@interface DUNamer : NSObject
{
    NSMutableDictionary *theData;
    NSCharacterSet *validCharacters;
    BOOL userSetName;
}

- (id)init;
- (id)initWithCharacterSet:(id)arg1;
- (void)dealloc;
- (void)setValidCharacterSet:(id)arg1;
- (void)setDefaultName:(id)arg1;
- (void)setDefaultFATName:(id)arg1;
- (void)setUserEnteredName:(id)arg1;
- (id)name:(BOOL)arg1;
- (id)nameWithFilesystem:(id)arg1;
- (void)dumpNamer;

@end

