/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol DUNotifierProtocol
- (void)notifyFrontmostModulesOnly:(id)arg1 diskNotification:(id)arg2;
@end

