/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol DUOutlineControllerProtocol
- (id)listView;
- (id)outlineView:(id)arg1 menuForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)outlineView:(id)arg1 willReturnMenu:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)disksChanged:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)fullListReceived:(id)arg1;
- (void)unselectAllDisks:(id)arg1;
- (void)reloadData;
- (void)resetSelectedDisks;
- (void)resetSelectedVolumes;
- (void)resetSelectedRAIDs;
- (void)addToSelectedDisks:(id)arg1;
- (void)addToSelectedVolumes:(id)arg1;
- (void)addToSelectedRAIDs:(id)arg1;
- (id)selectedDisks;
- (id)selectedVolumes;
- (id)selectedRAIDs;
- (id)allSelectedItems;
@end

