/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "DUWindowControllerProtocol-Protocol.h"

@interface DUProgressWindowController : NSObject <DUWindowControllerProtocol>
{
    BOOL interfaceLock;
    id _progressView;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (oneway void)beginProgressWithMessage:(id)arg1 withInformationText:(id)arg2 allowCancel:(BOOL)arg3 cancelButtonTitle:(id)arg4 allowSkip:(BOOL)arg5 skipButtonTitle:(id)arg6 usingDelegate:(id)arg7 andCancelSelector:(SEL)arg8 andSkipSelector:(SEL)arg9 andContext:(id)arg10;
- (oneway void)beginProgressWithOptions:(id)arg1;
- (oneway void)updateProgressOptions:(id)arg1;
- (oneway void)endProgress;
- (oneway void)setNeedsWarningOnQuit:(BOOL)arg1;
- (void)cancelButtonHit:(id)arg1;
- (void)skipButtonHit:(id)arg1;
- (id)window;
- (void)diskName:(id)arg1;
- (void)okButton:(id)arg1;
- (void)cancelButton:(id)arg1;
- (void)skipButton:(id)arg1;
- (id)selectedDisks;
- (id)selectedVolumes;
- (id)selectedRAIDs;
- (id)allSelectedItems;
- (id)allSelectedItems:(BOOL)arg1 filterDuplicates:(BOOL)arg2;
- (void)setInterfaceLock;
- (void)resetInterfaceLock;
- (BOOL)interfaceLock;
- (id)globalProgressBar;
- (void)setGlobalProgressBarValue:(double)arg1;
- (void)setGlobalProgressBarIndeterminate:(BOOL)arg1;
- (void)startGlobalProgressBarAnimation:(id)arg1;
- (void)stopGlobalProgressBarAnimation:(id)arg1;
- (void)activateGlobalProgressBar:(BOOL)arg1;
- (void)activateGlobalProgressText:(BOOL)arg1;
- (void)setGlobalProgressText:(id)arg1;
- (void)setSecondaryProgressText:(id)arg1;
- (void)setGlobalPersistentMessageText:(id)arg1;
- (void)setGlobalPersistentAttributedMessageText:(id)arg1;
- (BOOL)globalTextPersistent;
- (void)forceUpdateWindow:(id)arg1;
- (void)notifyWindowOfEvent:(id)arg1 diskNotification:(id)arg2;
- (void)notifyWindowOfCompletion:(id)arg1;
- (id)warnOnClose;
- (id)warnOnQuit;
- (id)warnOnSwitch;
- (BOOL)canPrint;
- (void)printModuleSpecific:(id)arg1;

@end

