/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/DURebuildRAIDManager.h>

@interface DURebuildRAIDManager (_DU_Private)
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)diskIsRebuilding:(id)arg1;
- (void)removeController:(id)arg1;
@end

