/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DURebuildRAIDController : NSObject
{
    id _progress;
    NSString *_diskIdentifier;
    NSString *_raidMemberUUID;
    double _status;
    BOOL _rebuilding;
    id _timeEstimator;
}

- (id)initWithDisk:(id)arg1;
- (void)dealloc;
- (void)trackRebuild:(id)arg1;
- (void)getProgress:(id)arg1;
- (void)periodicallyCheckRAIDRebuild:(id)arg1;
- (id)diskIdentifier;
- (id)raidMemberUUID;
- (void)cleanUpProgress;

@end

