/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSString;

@interface DUTimeEstimator : NSObject
{
    NSDate *knownStartTime;
    double knownStartPercent;
    NSDate *estimatedStartTime;
    NSDate *currentTime;
    double currentPercent;
    NSDate *actualCompletionTime;
    double persecond;
    double remaining;
    double averagePerSecond;
    BOOL firstTimeCalculation;
    long long rollingEstimateIndex;
    double rollingEstimate[10];
    NSDate *lastUpdate;
    double lastUpdatePercent;
    NSString *cachedTimeString;
}

- (id)init;
- (id)initWithPercentComplete:(double)arg1;
- (void)dealloc;
- (void)setStartTime;
- (void)setStartTime:(id)arg1;
- (void)setStartTime:(id)arg1 withPercentComplete:(double)arg2;
- (void)setCurrentPercentage:(double)arg1;
- (void)setCurrentTime;
- (void)setTaskComplete;
- (id)startTime;
- (id)actualCompletionTime;
- (id)estimatedCompletionTime;
- (double)currentCompletionPercent;
- (double)taskDuration;
- (id)timeString;
- (id)timeEstimateString;
- (id)timeEstimateString:(double)arg1;
- (id)durationString;
- (void)calculateTimeEstimates;
- (void)calculateStartTime;
- (void)resetTimers;
- (void)resetTimers:(BOOL)arg1;

@end

