/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSImage.h"

@interface NSImage (ZFSXSAdditions)
- (id)bitmapRepresentation;
- (id)negativeImage;
- (id)imageWithAlpha:(double)arg1;
- (id)imageBadgedWithImage:(id)arg1;
- (id)imageBadgedWithImage:(id)arg1 scaledToFractionOfWidth:(double)arg2;
- (void)drawCenteredInRect:(struct CGRect)arg1 fromRect:(struct CGRect)arg2 operation:(unsigned long long)arg3 fraction:(double)arg4;
@end

