/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSView.h"

@interface NSView (KeyViewExtensions)
- (void)addKeyViewAfter:(id)arg1;
- (void)addKeyViewBefore:(id)arg1;
- (void)displayKeyViewChain;
- (void)addKeyViewAtEndOf:(id)arg1;
- (void)removeKeyViewFromChain;
@end

