/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSBox, NSButton, NSImageView, NSProgressIndicator, NSString, NSTextField, NSView;

@interface ProgressViewController : NSObject
{
    NSView *_view;
    NSView *_progressView;
    NSButton *_progressCancelButton;
    NSButton *_progressSkipButton;
    NSTextField *_progressInformationTextField;
    NSTextField *_progressMessageTextField;
    NSProgressIndicator *_progressProgressIndicator;
    NSView *_alertView;
    NSButton *_alertOKButton;
    NSButton *_alertCancelButton;
    NSTextField *_alertTitleTextField;
    NSTextField *_alertMessageTextField;
    NSImageView *_alertImageView;
    NSBox *_separator;
    BOOL _progressCancelPending;
    BOOL _progressSkipPending;
    SEL _progressCancelSelector;
    SEL _progressSkipSelector;
    BOOL _alertOKPending;
    BOOL _alertCancelPending;
    SEL _alertOKSelector;
    SEL _alertCancelSelector;
    BOOL _needsWarningOnQuit;
    BOOL _isAlertView;
    id _delegate;
    id _context;
    NSString *_cachedPrimaryText;
    NSString *_cachedSecondaryText;
}

+ (id)progressViewController;
- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)startAnimation;

@end

