/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DUSupport/ProgressController.h>

@interface ProgressController (Accessors)
- (id)window;
- (long long)viewCount;
- (id)parent;
- (void)setParent:(id)arg1;
- (BOOL)excludeFromWindowsMenu;
- (void)setExcludeFromWindowsMenu:(BOOL)arg1;
- (BOOL)usesSound;
- (void)setUsesSound:(BOOL)arg1;
- (BOOL)recentAtTop;
- (BOOL)cachedRecentAtTop;
- (void)setRecentAtTop:(BOOL)arg1;
- (BOOL)animateInitialAppearance;
- (void)setAnimateInitialAppearance:(BOOL)arg1;
- (BOOL)animateResizing;
- (void)setAnimateResizing:(BOOL)arg1;
- (id)windowTitle;
- (void)setWindowTitle:(id)arg1;
- (id)frameAutosaveName;
- (void)setFrameautosaveName:(id)arg1;
@end

