/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSImage, NSString, NSValueTransformer;

@interface ZFSXSImageAndTextCell : NSTextFieldCell
{
    NSImage *_image;
    NSImage *_placeholderImage;
    struct CGSize _imageBounds;
    NSValueTransformer *_imageValueTransformer;
    NSString *_imageValueTransformerClassName;
    NSValueTransformer *_titleValueTransformer;
    NSString *_titleValueTransformerClassName;
    NSValueTransformer *_auxImageValueTransformer;
    NSString *_auxImageValueTransformerClassName;
    unsigned long long _verticalAlignment;
    NSImage *_auxImage;
    NSImage *_auxRolloverImage;
    BOOL _isUserAuxRolloverImage;
    BOOL _mouseDownInAuxImage;
    BOOL _mouseHoveredInAuxImage;
    SEL _auxAction;
    id _auxTarget;
    NSString *_imageKeyPath;
    NSString *_titleKeyPath;
    NSString *_auxImageKeyPath;
    struct CGRect _imageRect;
    struct CGRect _titleRect;
    struct CGRect _auxImageRect;
}

+ (struct CGSize)sizeProportionalToSize:(struct CGSize)arg1 constrainedBySize:(struct CGSize)arg2;
+ (BOOL)prefersTrackingUntilMouseUp;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setObjectValue:(id)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)auxiliaryImageRectForBounds:(struct CGRect)arg1;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)updateNeedsHighlightedTextFlagWithControlView:(id)arg1;
@property(retain) NSImage *auxiliaryRolloverImage; // @synthesize auxiliaryRolloverImage=_auxRolloverImage;
- (id)currentStatusImageForFrame:(struct CGRect)arg1;
- (id)_highlightedImageForImage:(id)arg1 frame:(struct CGRect)arg2;
- (id)_rolloverImageForImage:(id)arg1 frame:(struct CGRect)arg2;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (void)addTrackingAreasForView:(id)arg1 inRect:(struct CGRect)arg2 withUserInfo:(id)arg3 mouseLocation:(struct CGPoint)arg4;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property id auxiliaryTarget; // @synthesize auxiliaryTarget=_auxTarget;
@property SEL auxiliaryAction; // @synthesize auxiliaryAction=_auxAction;
@property(retain) NSImage *auxiliaryImage; // @synthesize auxiliaryImage=_auxImage;
@property(retain) NSString *auxiliaryImageValueTransformerClassName; // @synthesize auxiliaryImageValueTransformerClassName=_auxImageValueTransformerClassName;
@property(retain) NSString *titleValueTransformerClassName; // @synthesize titleValueTransformerClassName=_titleValueTransformerClassName;
@property(retain) NSString *imageValueTransformerClassName; // @synthesize imageValueTransformerClassName=_imageValueTransformerClassName;
@property unsigned long long verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
@property(retain) NSValueTransformer *auxiliaryImageValueTransformer; // @synthesize auxiliaryImageValueTransformer=_auxImageValueTransformer;
@property(retain) NSString *auxiliaryImageKeyPath; // @synthesize auxiliaryImageKeyPath=_auxImageKeyPath;
@property(retain) NSImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain) NSValueTransformer *titleValueTransformer; // @synthesize titleValueTransformer=_titleValueTransformer;
@property(retain) NSString *titleKeyPath; // @synthesize titleKeyPath=_titleKeyPath;
@property(retain) NSValueTransformer *imageValueTransformer; // @synthesize imageValueTransformer=_imageValueTransformer;
@property(retain) NSString *imageKeyPath; // @synthesize imageKeyPath=_imageKeyPath;
@property struct CGSize imageBounds; // @synthesize imageBounds=_imageBounds;
@property(retain) NSImage *image; // @synthesize image=_image;

@end

