/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTableView.h"

@class NSAttributedString, NSCell<XFSXSCellMouseTrackingProtocol>, NSString;

@interface ZFSXSTableView : NSTableView
{
    BOOL _trackingEnabled;
    long long _mouseRow;
    long long _mouseCol;
    NSCell<XFSXSCellMouseTrackingProtocol> *_mouseCell;
    NSAttributedString *_emptyTableAttributedString;
}

@property NSString *emptyTableString;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)keyDown:(id)arg1;
- (void)delete:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)updateTrackingAreas;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (id)preparedCellAtColumn:(long long)arg1 row:(long long)arg2;
- (void)updateCell:(id)arg1;
@property(getter=isTrackingEnabled) BOOL trackingEnabled; // @synthesize trackingEnabled=_trackingEnabled;
@property NSAttributedString *emptyTableAttributedString; // @synthesize emptyTableAttributedString=_emptyTableAttributedString;

@end

