/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSWindowDelegate-Protocol.h"

@class DRBurnSetupPanel, NSString;

@interface BurnController : NSObject <NSWindowDelegate>
{
    BOOL _canBeAppended;
    long long _sectorsNeeded;
    BOOL _skipFinalFreePartition;
    BOOL _optimize;
    DRBurnSetupPanel *_burnSetup;
    NSString *_digihubDeviceOFPath;
}

+ (id)burnController;
- (id)init;
- (void)dealloc;
- (id)runBurnPanel:(id)arg1 forDigihubDeviceOFPath:(id)arg2;
- (BOOL)setupPanelShouldHandleMediaReservations:(id)arg1;
- (void)beginBurnPanel:(id)arg1 forDigihubDeviceOFPath:(id)arg2 onWindow:(id)arg3 forSender:(id)arg4 withSelector:(SEL)arg5 context:(id)arg6;
- (void)setupPanelDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)prepareBurnDialog;
- (void)finishBurnDialog;

@end

