/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUAppDelegate.h"

@interface DUAppDelegate (DiskImageOpenFilesSupport)
- (id)selectDiskImageUsingWindow:(id)arg1 withTitle:(id)arg2 andDefaultButton:(id)arg3;
- (id)selectDiskImagesUsingWindow:(id)arg1 withTitle:(id)arg2 andDefaultButton:(id)arg3;
- (id)_selectDiskImagesUsingWindow:(id)arg1 allowMultiple:(BOOL)arg2 withTitle:(id)arg3 andDefaultButton:(id)arg4;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (BOOL)application:(id)arg1 openFile:(id)arg2;
- (void)application:(id)arg1 openFiles:(id)arg2;
- (void)doOpenFiles:(id)arg1;
@end

