/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUAppDelegate.h"

@interface DUAppDelegate (DUprivate)
- (void)endSheet:(id)arg1 returnCode:(long long)arg2;
- (id)logFileWithPath:(id)arg1;
- (id)logControllerWithLogFile:(id)arg1;
- (BOOL)nfsMountsAvailable;
- (void)doUnmount:(id)arg1 withForce:(BOOL)arg2;
@end

