/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOpenSavePanelDelegate-Protocol.h"

@class DMManager, DUDebug, DUDiskController, DUModuleManager, DUNFSMountsWindowController, NSDictionary, NSMenuItem, NSMutableArray, NSMutableDictionary, NSStatusItem, NSView, NSWindow;

@interface DUAppDelegate : NSObject <NSOpenSavePanelDelegate>
{
    DUDiskController *diskController;
    NSDictionary *aboutBoxOptions;
    BOOL disksAreReady;
    id infoMenuItem;
    id mountMenuItem;
    id ejectMenuItem;
    id journalMenuItem;
    id revealMenuItem;
    NSWindow *prefWindow;
    NSView *prefView;
    id _dockMenu;
    NSMenuItem *helpMenuItem;
    NSMenuItem *preferencesMenuItem;
    NSMenuItem *hideDiskUtilityMenuItem;
    NSMenuItem *servicesMenuItem;
    NSMenuItem *hideOthersMenuItem;
    NSMenuItem *showAllMenuItem;
    NSMenuItem *minimizeMenuItem;
    NSMenuItem *zoomMenuItem;
    NSMenuItem *bringAllToFrontMenuItem;
    NSMenuItem *logMenuItem;
    NSMenuItem *nfsMountConfigurationMenuItem;
    NSMenuItem *pageSetupMenuItem;
    NSMenuItem *printMenuItem;
    NSMenuItem *burnMenuItem;
    NSMenuItem *attachImageMenuItem;
    NSMenuItem *imagesMenuItem;
    NSMenuItem *imageDeviceMenuItem;
    NSMenuItem *checksumMenuItem;
    NSMenuItem *saveLogMenuItem;
    NSMenuItem *saveLogSelectionMenuItem;
    NSMenuItem *reloadMenuItem;
    NSMenuItem *deleteMenuItem;
    NSMenuItem *directoryMountMenuItem;
    DUDebug *debug;
    DMManager *dm;
    DUModuleManager *moduleManager;
    id logWindow;
    NSMutableArray *logItems;
    NSMutableDictionary *logFiles;
    DUNFSMountsWindowController *nfsMountConfigurationWindowController;
    id extendedInfoController;
    id iSCSIController;
    NSStatusItem *statusItem;
    SEL postLaunchSelector;
    id postLaunchData;
    SEL postLaunchChecksum;
    id postLaunchChecksumData;
    BOOL terminateMessageSent;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (id)diskController;
- (id)dm;
- (void)showPreferences:(id)arg1;
- (void)connect:(id)arg1;
- (void)disconnect:(id)arg1;
- (void)newDocument:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)displayAboutPanel:(id)arg1;
- (id)debugObject;
- (void)setDockMenu:(id)arg1;
- (id)applicationDockMenu:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)fullListReceived:(id)arg1;
- (void)notifyFrontmostModulesOnly:(id)arg1 diskNotification:(id)arg2;
- (void)printDocument:(id)arg1;
- (void)saveDocumentTo:(id)arg1;
- (void)saveSelectionTo:(id)arg1;
- (void)revertDocumentToSaved:(id)arg1;
- (void)deleteFile:(id)arg1;
- (void)setupDefaults;
- (void)handleDefaultsChanged:(id)arg1;
- (void)hidePreferencesMenuItem;
- (void)enableDebugMenu:(BOOL)arg1;
- (BOOL)debugMenuEnabled;
- (id)moduleManager;
- (void)dmToolDied:(id)arg1;
- (id)activeWindowController;
- (id)firstDUWindowControllerWindow;
- (id)moduleForName:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)mountSelected:(id)arg1;
- (void)forceUnmountSelected:(id)arg1;
- (void)unmountSelected:(id)arg1;
- (void)ejectSelected:(id)arg1;
- (void)makeJournaled:(id)arg1;
- (void)configureiSCSI:(id)arg1;
- (void)revealSelected:(id)arg1;
- (void)openSelected:(id)arg1;
- (void)displayEjectError:(id)arg1 withController:(id)arg2;
- (void)displayUnmountError:(id)arg1 withController:(id)arg2;
- (void)displayMountError:(id)arg1 withController:(id)arg2;
- (void)newImageSelected:(id)arg1;
- (void)iffSelected:(id)arg1;
- (void)ifdSelected:(id)arg1;
- (void)updateMenusForLog;
- (void)updateMenusForMain;
- (void)updateMenusForSingle;
- (void)attachImageSelected:(id)arg1;
- (void)chpassSelected:(id)arg1;
- (void)verifyImageSelected:(id)arg1;
- (void)checksumDeviceSelected:(id)arg1;
- (void)convertImageSelected:(id)arg1;
- (void)burnImageSelected:(id)arg1;
- (void)resizeImageSelected:(id)arg1;
- (void)imageScanSelected:(id)arg1;
- (void)openNFSMountsConfigurationWindow:(id)arg1;
- (void)nfsMountsConfigurationWindowClosed:(id)arg1;
- (void)openLogWindow:(id)arg1;
- (void)handleLogFileChanged:(id)arg1;
- (void)logWindowClosed:(id)arg1;
- (void)handleSelectionChanged:(id)arg1;
- (void)imageControllerOperationFinished:(id)arg1;
- (void)imageDoubleClicked:(id)arg1;
- (void)delayedChecksum:(id)arg1;
- (void)checksumCRC32:(id)arg1 userData:(id)arg2 error:(id *)arg3;
- (void)checksumMD5:(id)arg1 userData:(id)arg2 error:(id *)arg3;

@end

