/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUAppDelegate.h"

@interface DUAppDelegate (SelfTest)
- (void)application:(id)arg1 runTest:(unsigned long long)arg2 duration:(double)arg3;
@end

