/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSDocument.h"

@interface DUDocument : NSDocument
{
}

- (id)init;
- (void)dealloc;
- (BOOL)isDocumentEdited;
- (void)makeWindowControllers;
- (void)switchToFullDiskUtilityMode:(id)arg1;
- (void)singleWindowWithOptions:(id)arg1;
- (void)windowControllerDidLoadNib:(id)arg1;
- (id)createSingleFunctionWithName:(id)arg1 disk:(id)arg2;

@end

