/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (Operations)
- (void)newImage:(id)arg1;
- (void)verifyImage:(id)arg1;
- (void)checksumDevice:(id)arg1 withAlg:(id)arg2;
- (void)attachImageWithURL:(id)arg1;
- (void)changePassword:(id)arg1;
- (void)scanImage:(id)arg1;
- (void)convertImage:(id)arg1 window:(id)arg2;
- (void)resizeImage:(id)arg1 window:(id)arg2;
- (void)resizeImageSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)imageFolder:(id)arg1 window:(id)arg2;
- (void)imageDevice:(id)arg1 window:(id)arg2;
- (void)burnImage:(id)arg1;
@end

