/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (Support)
- (void)sendDelegateMessage:(SEL)arg1;
- (void)messageWithMessage:(id)arg1;
- (void)alertWithMessage:(id)arg1 error:(long long)arg2;
- (void)alertOK:(id)arg1;
- (void)progressDone:(id)arg1;
- (void)progressStartWithTitle:(id)arg1;
- (void)progressStartWithTitle:(id)arg1 withCancel:(BOOL)arg2;
- (void)handleAppBecameActiveNotification:(id)arg1;
- (void)progressUpdateMainThread:(id)arg1;
- (void)progressCanceled:(id)arg1;
- (void)progressSkipped:(id)arg1;
@end

