/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSoundDelegate-Protocol.h"

@class DUDisk, NSConditionLock, NSLock, NSString, ProgressViewController;

@interface DUImageController : NSObject <NSSoundDelegate>
{
    DUDisk *_diskToBeSelected;
    BOOL _selectPartitionTab;
    ProgressViewController *_pvc;
    BOOL _sheetPending;
    NSString *_pendingSheetMessage;
    double _maxVal;
    BOOL _asrInProgress;
    DUDisk *_asrDiskBeingScanned;
    id _delegate;
    BOOL _cancelFlag;
    BOOL _canCancel;
    BOOL _canSkip;
    BOOL _skipFlag;
    NSLock *_flagLock;
    NSString *_lastProgressMessage;
    NSString *_lastStage;
    id _timeEstimator;
    NSConditionLock *_burnRunPanelLock;
}

- (id)init;
- (void)dealloc;

@end

