/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "ODQueryDelegate-Protocol.h"

@class DUNFSMountsWindowController, NSArrayController, NSButton, NSMatrix, NSMultiReadUniWriteLock, NSMutableArray, NSProgressIndicator, NSTableView, NSTextField, NSWindow, ODNode, ODQuery, SFAuthorization;

@interface DUMountsController : NSObject <ODQueryDelegate>
{
    DUNFSMountsWindowController *windowController;
    NSTableView *mountsTableView;
    NSArrayController *mountsController;
    NSButton *addMountButton;
    NSButton *editMountButton;
    NSButton *deleteMountButton;
    NSWindow *editMountSheet;
    NSTextField *editMountSheetURLTextField;
    NSTextField *editMountSheetLocationTextField;
    NSMatrix *editMountSheetOptionsMatrix;
    NSTextField *editMountSheetAdvParamsTextField;
    NSButton *editMountSheetOKButton;
    NSButton *editMountSheetCancelButton;
    NSWindow *verifyMountSheet;
    NSTextField *verifyMountSheetHeaderText;
    NSTextField *verifyMountSheetBodyText;
    NSProgressIndicator *verifyMountSheetProgressIndicator;
    NSButton *verifyMountSheetOKButton;
    NSButton *verifyMountSheetCancelButton;
    SFAuthorization *_auth;
    ODNode *_localODNode;
    ODNode *_configODNode;
    ODQuery *_mountsQuery;
    BOOL _mountBeingEditedIsNew;
    BOOL _mountsModified;
    BOOL _verifyingMount;
    BOOL _mountVerificationSucceeded;
    NSMutableArray *_deletedMounts;
    NSMultiReadUniWriteLock *_contactingNFSServerLock;
    BOOL _contactingNFSServer;
    BOOL _cancelAttemptToContactNFSServer;
    BOOL _nfsServerResponded;
}

- (void)addOrEditMountButtonHit:(id)arg1;
- (void)editMountSheetButtonHit:(id)arg1;
- (void)verifyMountSheetButtonHit:(id)arg1;
- (void)mountsOptionsMatrixClicked:(id)arg1;
- (void)saveMounts:(id)arg1;
- (void)query:(id)arg1 foundResults:(id)arg2 error:(id)arg3;
@property BOOL mountsModified; // @synthesize mountsModified=_mountsModified;

@end

