/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface DUSimpleTable : NSObject
{
    NSTimer *theTimer;
    id windowController;
    double count;
    BOOL longRunning;
}

- (id)initWithTimer:(id)arg1 withController:(id)arg2 withCount:(double)arg3;
- (void)dealloc;
- (id)timer;
- (id)windowController;
- (double)count;
- (double)incrementCount;
- (void)setLongRunning:(BOOL)arg1;
- (BOOL)longRunning;

@end

