/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSException.h"

@interface MountsException : NSException
{
}

+ (id)name:(id)arg1 reason:(id)arg2 error:(id)arg3;
+ (void)raiseWithError:(id)arg1;
- (void)finalize;
- (long long)status;
- (id)statusString;

@end

