/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "PartitionSchemesHelper.h"

@interface PartitionSchemesHelper (DUPrivate)
- (id)findAndRemoveItem:(id)arg1 withDesc:(id)arg2;
- (id)prettySort:(id)arg1;
@end

