/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface PartitionSchemesHelper : NSObject
{
    NSArray *_layoutArray;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)loadData;
- (id)allDescriptions;
- (long long)countLayoutInfo;
- (id)layoutInfoForDescription:(id)arg1;
- (id)layoutInfoForKey:(id)arg1;
- (id)keyFromDescription:(id)arg1;
- (id)descriptionFromKey:(id)arg1;
- (long long)overheadFromLayoutInfo:(id)arg1;
- (id)descriptionFromLayoutInfo:(id)arg1;
- (id)layoutKeyFromLayoutInfo:(id)arg1;
- (BOOL)layoutIsNONE:(id)arg1;
- (BOOL)layoutIsGPT:(id)arg1;
- (BOOL)layoutIsMBR:(id)arg1;
- (BOOL)layoutIsApple:(id)arg1;

@end

