/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSBox, NSButton, NSDictionary, NSMatrix, NSOutlineView, NSPopUpButton, NSTextField, NSWindow;

@interface ResizeController : NSObject
{
    NSWindow *window;
    NSButton *cancelButton;
    NSTextField *imageNameTextField;
    NSTextField *minSizeTextField;
    NSTextField *maxSizeTextField;
    NSTextField *newSizeTextField;
    NSTextField *newSizeTitle;
    NSTextField *originalSizeTextField;
    NSTextField *originalSizeTitle;
    NSButton *resizeButton;
    NSPopUpButton *unitsPopUpButton;
    NSButton *partitionSelectorToggleButton;
    NSBox *resizeOptionsBox;
    NSMatrix *resizeOptionsMatrix;
    NSOutlineView *resizePartitionTable;
    id _modalDelegate;
    void *_contextInfo;
    NSDictionary *_resizeParameters;
    void *_theDiskImage;
    void *_deferredReleaseDiskImageRef;
    long long _units;
    long long _origSectorCount;
    long long _newSectorCount;
    long long _minSectorCount;
    long long _maxSectorCount;
    long long _granularity;
    NSDictionary *_resizeInfo;
    long long _resizeType;
    long long _selectedPartitionIndex;
    long long _minWindowHeight;
    long long _maxWindowHeight;
    BOOL _optionsRevealed;
}

- (id)initWithDiskImage:(void *)arg1 modalDelegate:(id)arg2 andContextInfo:(void *)arg3;
- (void)dealloc;
- (void)awakeFromNib;
- (void)runResizeImageSheetForWindow:(id)arg1;
- (void)resizeImageSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)loadFromNibIfNecessary:(id)arg1;
- (BOOL)setupResizePanel;
- (void)handleCancel:(id)arg1;
- (void)handleResize:(id)arg1;
- (void)handleSizeChanged:(id)arg1;
- (void)handleUnitsPopUpButtonChange:(id)arg1;
- (void)handleResizeOptionsMatrixChange:(id)arg1;
- (void)handlePartitionSelectedChange:(id)arg1;
- (void)handleTogglePartitionSelector:(id)arg1;

@end

