/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ResizeController.h"

@interface ResizeController (Utilities)
- (void)loadResizeInfo;
- (void)chooseBestPartition;
- (id)currentResizeContentInfoForPartition:(long long)arg1 returningCurrent:(long long *)arg2 andMin:(long long *)arg3 andMax:(long long *)arg4 andGran:(long long *)arg5;
- (void)syncResizeMatrix;
- (void)syncLimits;
- (int)allowsUnits:(long long)arg1;
- (void)syncSizeControlsAndDisplay;
- (void)syncSizeStringsWithUnits;
- (double)sizeForSectors:(long long)arg1 units:(long long)arg2;
- (id)descriptionFromSectors:(long long)arg1 units:(long long)arg2 dropScale:(int)arg3;
@end

