/*
 *     Generated by code-dump 1.05a.
 */
#import "NSTextField.h"

@interface DragTextField : NSTextField
{
    id dragDelegate;
}

- (unsigned int)draggingEntered:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (id)dragDelegate;
- (void)setDragDelegate:(id)fp8;

@end

