/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOpenSavePanelDelegate-Protocol.h"

@interface DUAppDelegateIFFFilter : NSObject <NSOpenSavePanelDelegate>
{
}

+ (id)iffFilter;
- (BOOL)panel:(id)arg1 shouldShowFilename:(id)arg2;

@end

