/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class DUDiskController, NSLock, NSMenu, NSMutableArray;

@interface DUDebug : NSObject
{
    DUDiskController *diskController;
    NSMenu *debugMenu;
    NSMutableArray *timerArray;
    NSLock *listLock;
    id progressController;
    id pwc;
}

- (id)init;
- (void)dealloc;
- (void)setupNotificationHandlers;
- (void)installDebugMenu;
- (void)removeDebugMenu;
- (id)diskController;
- (void)listAllDisks:(id)arg1;
- (void)listAllDisksWithProperties:(id)arg1;
- (void)longRunningProgress:(id)arg1;
- (void)thousandMinuteCountdown:(id)arg1;
- (void)tenThousandLineFirstAid:(id)arg1;
- (void)cancelButton:(id)arg1;
- (void)skipButton:(id)arg1;
- (void)startProgressBar:(id)arg1;
- (void)stopProgressBar:(id)arg1;
- (void)setIndeterminate:(id)arg1;
- (void)forceDiskUpdate:(id)arg1;
- (void)toggleNotifications:(id)arg1;
- (void)toggleShowEveryPartition:(id)arg1;
- (void)toggleUseTimeEstimateForDiscRecording:(id)arg1;
- (void)debugMessageLevelChange:(id)arg1;
- (id)findTimerInfo:(id)arg1;
- (void)setRunning:(BOOL)arg1;
- (void)stopRunning:(id)arg1;
- (void)timerTest:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

@end

