/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUBaseDiskListViewController.h"

@class NSArray;

@interface DUDiskListViewController : DUBaseDiskListViewController
{
    NSArray *draggedImages;
}

- (void)dealloc;
- (void)awakeFromNib;
- (void)delete:(id)arg1;
- (id)outlineView:(id)arg1 menuForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (BOOL)validDropItem:(id)arg1;
- (BOOL)validMovingItem:(id)arg1;
- (long long)getListPositionOfItem:(id)arg1 withIndex:(long long)arg2;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)outlineView:(id)arg1 willReturnMenu:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)tableViewDidEndDragOutsideBounds:(id)arg1;
- (void)imageDoubleClicked:(id)arg1;

@end

