/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (Accessors)
- (id)flagLock;
- (BOOL)cancelFlag;
- (void)setCancelFlag:(BOOL)arg1;
- (BOOL)canCancel;
- (void)setCanCancel:(BOOL)arg1;
- (BOOL)skipFlag;
- (void)setSkipFlag:(BOOL)arg1;
- (void)clearFlags;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)pvc;
- (id)asrDisk;
@end

