/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (AttachSupport)
- (void)attachThread:(id)arg1;
- (id)buildAttachDictFromURL:(id)arg1;
- (void)attachFinished:(id)arg1;
- (void)attachFailed:(id)arg1;
@end

