/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (CreateSupport)
- (void)gotNewImageParameters:(id)arg1 info:(id)arg2;
- (void)startNewImageOp:(id)arg1;
- (void)creationThread:(id)arg1;
- (void)createFinished:(id)arg1;
- (void)createFailed:(id)arg1;
@end

