/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (ConvertSupport)
- (void)gotConvertImageParameters:(id)arg1 info:(id)arg2;
- (void)startConvertImageOp:(id)arg1 image:(id)arg2;
- (void)conversionThread:(id)arg1;
- (void)convertFinished:(id)arg1;
- (void)convertFailed:(id)arg1;
@end

