/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (IFDSupport)
- (void)gotIFDImageParameters:(id)arg1 info:(id)arg2;
- (void)startIFDOp:(id)arg1 disk:(id)arg2;
- (void)ifdThread:(id)arg1;
- (void)ifdFinished:(id)arg1;
- (void)ifdFailed:(id)arg1;
@end

