/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (BurnSupport)
- (void)burnThread:(id)arg1;
- (void)burnRunPanel:(id)arg1;
- (void)burnPanelComplete:(id)arg1 info:(id)arg2;
- (void)burnResumeThreadWithPanelResult:(id)arg1 returningThreadOptions:(id)arg2;
- (void)burnFinishedSound:(id)arg1;
- (void)burnFinished:(id)arg1;
@end

