/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUImageController.h"

@interface DUImageController (ChecksumSupport)
- (void)checksumThread:(id)arg1;
- (id)decodeChecksumType:(id)arg1;
- (void)checksumFinished:(id)arg1;
@end

