/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSURL;

@interface DULogFile : NSObject
{
    NSURL *logFileURL;
    unsigned long long stringEncoding;
    BOOL isDeletable;
    BOOL autoOpen;
}

- (id)initWithDictionary:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (id)path;
- (unsigned long long)stringEncoding;
- (void)setStringEncoding:(unsigned long long)arg1;
- (BOOL)isDeletable;
- (BOOL)autoOpen;
- (void)setAutoOpen:(BOOL)arg1;

@end

