/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "NSWindowDelegate-Protocol.h"

@class NSButton, NSTextField, NSView;

@interface DUPreferenceWindowController : NSWindowController <NSWindowDelegate>
{
    NSView *diPrefContentView;
    NSTextField *diPrefTitleTextField;
    NSButton *diPrefVerifyChecksumsCheckbox;
    NSButton *diPrefCheckRemoteImagesCheckbox;
    NSButton *diPrefCheckLockedImagesCheckbox;
    NSButton *diPrefAutoOpenROCheckbox;
    NSButton *diPrefAutoOpenRWCheckbox;
    NSButton *diPrefMoveToTrashCheckbox;
    NSButton *diPrefRevealImagesCheckbox;
    NSButton *diPrefHelpButton;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)windowDidLoad;
- (void)windowDidBecomeKey:(id)arg1;
- (void)verifyChecksumsAction:(id)arg1;
- (void)checkRemoteImagesAction:(id)arg1;
- (void)checkLockedImagesAction:(id)arg1;
- (void)autoOpenROAction:(id)arg1;
- (void)autoOpenRWAction:(id)arg1;
- (void)moveToTrashAction:(id)arg1;
- (void)revealImagesAction:(id)arg1;
- (void)helpButtonAction:(id)arg1;

@end

