/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUBaseWindowController.h"

#import "DUSingleFunctionWindowControllerProtocol-Protocol.h"

@class DUDisk, DUModule, NSImageView, NSMenu, NSProgressIndicator, NSString, NSTabView, NSTextField;

@interface DUSingleFunctionWindowController : DUBaseWindowController <DUSingleFunctionWindowControllerProtocol>
{
    NSTextField *singleInterfaceWorkingDiskName;
    NSTabView *singleInterfaceBundleView;
    NSTextField *singleInterfaceProgressText;
    NSProgressIndicator *singleInterfaceProgressBar;
    NSImageView *singleInterfaceWorkingDiskIcon;
    NSMenu *objectMenu;
    NSString *moduleType;
    DUDisk *objectDisk;
    DUModule *module;
    BOOL globalTextPersistent;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)windowDidLoad;
- (void)windowIsClosing:(id)arg1;
- (void)loadModuleBundle:(id)arg1;
- (void)setDiskNameField;
- (void)hideDiskInfo:(BOOL)arg1;
- (id)windowTitleForDocumentDisplayName:(id)arg1;
- (void)setMenu:(id)arg1;
- (void)setModuleType:(id)arg1;
- (id)moduleType;
- (void)setDisk:(id)arg1;
- (id)disk;
- (void)diskName:(id)arg1;
- (id)selectedDisks;
- (id)selectedVolumes;
- (id)selectedRAIDs;
- (id)allSelectedItems;
- (id)allSelectedItems:(BOOL)arg1 filterDuplicates:(BOOL)arg2;
- (id)globalProgressBar;
- (void)setGlobalProgressBarValue:(double)arg1;
- (void)setGlobalProgressBarIndeterminate:(BOOL)arg1;
- (void)startGlobalProgressBarAnimation:(id)arg1;
- (void)stopGlobalProgressBarAnimation:(id)arg1;
- (void)activateGlobalProgressBar:(BOOL)arg1;
- (void)activateGlobalProgressText:(BOOL)arg1;
- (void)setGlobalProgressText:(id)arg1;
- (void)setGlobalPersistentMessageText:(id)arg1;
- (void)setGlobalPersistentAttributedMessageText:(id)arg1;
- (BOOL)globalTextPersistent;
- (void)notifyWindowOfEvent:(id)arg1 diskNotification:(id)arg2;
- (id)warnOnClose;
- (id)warnOnQuit;
- (BOOL)canPrint;
- (void)printModuleSpecific:(id)arg1;

@end

