/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSTextViewDelegate-Protocol.h"

@class DUWindowControllerInfoPanel, NSLock, NSMutableDictionary, NSMutableParagraphStyle, NSTextView;

@interface DUTwoColumnInfo : NSObject <NSTextViewDelegate>
{
    NSTextView *view;
    DUWindowControllerInfoPanel *_controller;
    NSMutableParagraphStyle *paragraphStyle;
    NSMutableParagraphStyle *paragraphMiddleStyle;
    NSMutableDictionary *storedText;
    NSLock *statusViewLock;
    BOOL locked;
    BOOL gFirstTime;
    unsigned long long specialKeys[5][2];
}

- (id)initWithTextField:(id)arg1;
- (void)dealloc;
- (id)controller;
- (void)awakeFromNib;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)storedText;
- (void)setInterfaceLocked;
- (void)clearTextOnMainThread:(id)arg1;
- (void)clearText;
- (id)view;
- (void)addStringNormal:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringNormal:(id)arg1 withTitle:(id)arg2 row:(unsigned long long)arg3 column:(unsigned long long)arg4;
- (void)addStringError:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringTitle:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringInactive:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringLink:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringNSURL:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3 url:(id)arg4;
- (void)addStringLocalFile:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)addStringSizeInBytes:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)markSpecial:(long long)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)boundsChanged:(id)arg1;
- (void)calculateTabs:(double)arg1 width2:(double)arg2 width3:(double)arg3;
- (void)pushTextToDisplay:(id)arg1;
- (void)displayText;

@end

