/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DUWindowController.h"

@interface DUWindowController (SelfTest)
- (id)hiddenModulesForDisk:(id)arg1;
- (id)moduleWithName:(id)arg1;
- (void)selfTestVisibleModulesForDisk:(id)arg1 withTimingInfo:(id)arg2;
- (BOOL)selectDiskInDiskListByDMDisk:(id)arg1;
@end

