/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "DUWindowControllerProtocol-Protocol.h"

@class DMManager, DUDisk, DUTwoColumnInfo, DUWindowController, NSImage, NSImageView, NSProgressIndicator, NSTextField, NSTextView, NSView;

@interface DUWindowControllerInfoPanel : NSObject <DUWindowControllerProtocol>
{
    NSView *statusAreaView;
    DUWindowController *winController;
    NSProgressIndicator *progressBar;
    NSTextField *progressBarText;
    DUTwoColumnInfo *twoColumnInfoPanel;
    NSTextView *twoColumnInfoPanelTextView;
    NSImageView *infoIcon;
    DMManager *dm;
    DUDisk *workingDisk;
    BOOL globalTextPersistent;
    id _lastMessage;
    NSImage *imageIcon;
}

- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)setNotificationHandlers:(id)arg1;
- (id)dm;
- (void)setStartupFrame:(struct CGSize)arg1;
- (id)statusAreaView;
- (id)workingDisk;
- (void)setWorkingDisk:(id)arg1;
- (id)globalProgressWheel;
- (void)setImageIcon:(id)arg1;
- (void)clearAllData:(id)arg1;
- (void)updateWorkingDiskInfo;
- (void)diskChangedHandler:(id)arg1;
- (void)diskReplacedByHandler:(id)arg1;
- (void)interfaceLockChanged:(id)arg1;
- (void)selectionDidChange:(id)arg1;
- (void)updateDisk;
- (void)updateSession;
- (void)updateVolume;
- (void)updateRAIDSliceDisk;
- (void)updateRAIDSetDisk;
- (void)updateDiskImage;
- (void)updateOfflineDiskImage;
- (void)updateRAIDVolume;
- (void)updateOpticalDevice;
- (void)updateZFS;
- (void)updateZFSFilesystem;
- (void)forceUpdateWindow:(id)arg1;
- (void)setInterfaceLock;
- (void)resetInterfaceLock;
- (BOOL)interfaceLock;
- (id)selectedDisks;
- (id)selectedVolumes;
- (id)selectedRAIDs;
- (id)allSelectedItems;
- (id)allSelectedItems:(BOOL)arg1 filterDuplicates:(BOOL)arg2;
- (id)globalProgressBar;
- (void)setGlobalProgressBarValue:(double)arg1;
- (void)setGlobalProgressBarIndeterminate:(BOOL)arg1;
- (void)startGlobalProgressBarAnimation:(id)arg1;
- (void)stopGlobalProgressBarAnimation:(id)arg1;
- (void)activateGlobalProgressBar:(BOOL)arg1;
- (void)activateGlobalProgressText:(BOOL)arg1;
- (void)setGlobalProgressText:(id)arg1;
- (void)setGlobalPersistentMessageText:(id)arg1;
- (void)setGlobalPersistentAttributedMessageText:(id)arg1;
- (BOOL)globalTextPersistent;
- (id)warnOnClose;
- (id)warnOnQuit;
- (id)warnOnSwitch;
- (BOOL)canPrint;
- (void)printModuleSpecific:(id)arg1;
- (id)lastMessage;
- (void)setLastMessage:(id)arg1;
- (void)notifyWindowOfEvent:(id)arg1 diskNotification:(id)arg2;
- (void)notifyWindowOfCompletion:(id)arg1;

@end

