/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface FormatHelper : NSObject
{
}

+ (id)sharedInstance;
- (id)init;
- (id)allDescriptions;
- (id)descriptionFromKey:(id)arg1;
- (id)keyFromDescription:(id)arg1;
- (id)extensionFromDescription:(id)arg1;
- (BOOL)formatUsesVirtualDiskSizeFromDescription:(id)arg1;

@end

