/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOpenSavePanelDelegate-Protocol.h"

@class CryptoHelper, DiskSizesHelper, FormatHelper, NSPopUpButton, NSSavePanel, NSTextField, NSView, PartitionSchemesHelper, VolumeFormatsHelper;

@interface NewBlankImageController : NSObject <NSOpenSavePanelDelegate>
{
    NSPopUpButton *_volumeFormatPopup;
    NSTextField *_volumeNameField;
    NSTextField *_volumeNameFieldTitle;
    NSView *_accessoryView;
    NSPopUpButton *_encryptPopup;
    NSPopUpButton *_volumeSizePopup;
    NSPopUpButton *_imageFormatPopup;
    NSPopUpButton *_partitionSchemePopup;
    CryptoHelper *_cryptoHelper;
    PartitionSchemesHelper *_partitionSchemeHelper;
    DiskSizesHelper *_diskSizesHelper;
    FormatHelper *_imageFormatHelper;
    VolumeFormatsHelper *_volumeFormatHelper;
    NSSavePanel *_savePanel;
    long long _volumeSizeInSectors;
    long long _volumeSizeUnits;
    long long _freeSpaceOnCurrentDrive;
    long long _volumeFormatMinSize;
    long long _volumeFormatMaxSize;
    long long _partitionSchemeOverhead;
}

+ (id)newBlankImageController;
- (id)init;
- (void)dealloc;
- (id)getNewBlankImageParameters;
- (void)beginGettingImageParametersOnWindow:(id)arg1 forSender:(id)arg2 withSelector:(SEL)arg3 context:(id)arg4;
- (void)savePanelDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)getAccessoryView;
- (void)cleanupAccessoryView;
- (void)setupAccessoryView;
- (void)panel:(id)arg1 directoryDidChange:(id)arg2;
- (void)updateFreeSpaceAt:(id)arg1;
- (void)encryptPopupChanged:(id)arg1;
- (void)imageFormatPopupChanged:(id)arg1;
- (void)volumeNameFieldChanged:(id)arg1;
- (void)volumeSizePopupChanged:(id)arg1;
- (void)layoutPopupChanged:(id)arg1;
- (void)volumeFormatPopupChanged:(id)arg1;

@end

