/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NewBlankImageController.h"

@interface NewBlankImageController (ControlSynchronizationAndRationalization)
- (void)synchronizeFileExtensionWithImageFormat;
- (void)synchronizeVolumeSizePopup:(long long)arg1;
- (BOOL)rationalizePartitionSchemeWithVolumeFormat;
- (BOOL)rationalizeImageSizeWithVolumeFormatAndPartitionScheme;
- (long long)pinSizeToLimits:(long long)arg1;
- (void)warnOnImageSizeChangeFrom:(long long)arg1 to:(long long)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)determineVolumeFormatSizeLimits;
- (void)rationalizeVolumeNameFieldWithVolumeFormat;
- (void)determineLayoutOverhead;
@end

