/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ResizeController.h"

@interface ResizeController (Accessors)
- (id)resizeParameters;
- (void)setResizeParameters:(id)arg1;
- (id)_resizeInfo;
- (void)_setResizeInfo:(id)arg1;
- (void *)contextInfo;
- (void)setContextInfo:(void *)arg1;
- (id)modalDelegate;
- (void)setModalDelegate:(id)arg1;
- (void *)diskImageRef;
- (void)deferredDiskImageRelease:(id)arg1;
- (void)setDiskImageRef:(void *)arg1;
- (long long)minSectorCount;
- (void)setMinSectorCount:(long long)arg1;
- (long long)maxSectorCount;
- (void)setMaxSectorCount:(long long)arg1;
- (long long)granularity;
- (void)setGranularity:(long long)arg1;
- (BOOL)hasPartitions;
- (long long)partitionCount;
- (long long)minWindowHeight;
- (void)setMinWindowHeight:(long long)arg1;
- (long long)maxWindowHeight;
- (void)setMaxWindowHeight:(long long)arg1;
@end

