/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface SenderInfo : NSObject
{
    id _object;
    SEL _selector;
    id _extraInfo;
}

- (id)init;
- (void)dealloc;
- (id)object;
- (void)setObject:(id)arg1;
- (SEL)selector;
- (void)setSelector:(SEL)arg1;
- (id)extraInfo;
- (void)setExtraInfo:(id)arg1;

@end

