/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface DMManagerPrivVars : NSObject
{
    struct __DASession *_clientDefaultDASession;
    struct __CFRunLoop *_clientRunLoop;
    unsigned int _bootstrap_MachPort;
    char _sessionUUID[40];
    unsigned int _f2t_MachPort;
    unsigned int _t2f_MachPort;
    struct {
        unsigned int _field1;
        unsigned int _field2;
        unsigned int _field3;
        unsigned int _field4;
        unsigned int _field5;
        int _field6;
    } *_msgReplyArea;
    struct __CFMachPort *_t2f_CFMachPort;
    struct __CFRunLoopSource *_t2f_CFRunLoopSource;
    struct AuthorizationOpaqueRef *_authorization;
}

@end

