/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface DMManager : NSObject
{
    id _instPriv;
}

+ (BOOL)systemResourcesSufficient;
+ (id)sharedManager;
+ (id)sharedManagerForThread;
- (id)init;
- (void)setDefaultDASession:(struct __DASession *)arg1;
- (void)setLanguage:(id)arg1;
- (int)setUserID:(id)arg1 groupID:(id)arg2;
- (void)done;
- (void)dealloc;
- (void)finalize;

@end

