/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <DiskManagement/DMManager.h>

@interface DMManager (EmulationAdditions)
- (void)waitForAppearanceOfDiskNodes;
- (id)diskWithIdentifier:(id)arg1;
- (id)rootDisk;
- (id)directChildrenOfDisk:(id)arg1;
- (int)partitionMapTypeForDisk:(id)arg1;
@end

