/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface DMRepairDisk : NSObject
{
    id _instPriv;
}

- (id)init;
- (id)initWithManager:(id)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)cancelCurrentOperation;
- (id)userAccountsForDisk:(struct __DADisk *)arg1 getError:(int *)arg2;
- (int)beginResetUserPermissionsForDisk:(struct __DADisk *)arg1 forUID:(long long)arg2 level:(long long)arg3;
- (int)beginFilesystemVerifyOrRepairForDisk:(struct __DADisk *)arg1 repair:(BOOL)arg2;
- (int)beginFilesystemVerifyForDisk:(struct __DADisk *)arg1;
- (int)beginFilesystemRepairForDisk:(struct __DADisk *)arg1;
- (int)beginPermissionsVerifyOrRepairForDisk:(struct __DADisk *)arg1 repair:(BOOL)arg2;
- (int)beginPermissionsVerifyForDisk:(struct __DADisk *)arg1;
- (int)beginPermissionsRepairForDisk:(struct __DADisk *)arg1;

@end

