/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@interface DMUDSWrapper : NSObject <NSCoding>
{
    struct DMUDSPrivRec _myUDS;
}

+ (id)wrapperWithUDS:(struct DMUDSPrivRec *)arg1;
+ (id)wrapperFromDADisk:(struct __DADisk *)arg1;
- (id)initWithUDS:(struct DMUDSPrivRec *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (struct DMUDSPrivRec *)UDSPtr;
- (id)wholeDiskWrapper;
- (id)description;
- (BOOL)isEqual:(id)arg1;

@end

